mv_forum_parser_forums:
    path:     /
    defaults: { _controller: MVForumParserBundle:Main:getForums }
    methods:   [GET]

mv_forum_parser_topics:
    path:     /getTopics/{slug_forum}
    defaults: { _controller: MVForumParserBundle:Main:getTopics }
    methods:   [GET]
