mv_forum_parser_forums:
  path:     /
  defaults: { _controller: MVForumParserBundle:Main:getForums }
  methods:   [GET]

mv_forum_parser_topics:
  path:     /getTopics/{slug_forum}/{page}
  defaults: { _controller: MVForumParserBundle:Main:getTopics, page: 1 }
  methods:   [GET]
  requirements:
    page: \d+

mv_forum_parser_posts:
  path: /getPost/{slug_forum}/{slug_post}/{page}
  defaults: { _controller: MVForumParserBundle:Posts:getPosts, page: 1 }
  methods: [GET]
  requirements:
    page: \d+

mv_forum_parser_login:
  path: /login
  defaults: { _controller: MVForumParserBundle:Login:login }
  methods: [POST]